language: python
python:
    - "2.7"
before_install:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
    - sudo apt-get update
    - sudo apt-get install mongodb-10gen
    - sudo service mongodb start
install:
    - pip install -r requirements.txt --use-mirrors
script: nosetests
notifications:
    email: false